dist: bionic
language: cpp
sudo: true
compiler: gcc

before_install:
    - sudo apt-get update -q
install:
    - sudo apt-get install -y -q libnetfilter-queue-dev libpcap-dev g++ libboost-all-dev automake libtool git libglib2.0-dev g++ libjson-c-dev libxen-dev byacc make netcat libelf-dev libssl-dev flex libdwarf-dev cmake flex bison libglib2.0-dev libvirt-dev libjson-c-dev libyajl-dev colormake libssh-dev libcurl4-openssl-dev uuid-dev
script:
    - git submodule update --init
    - mkdir build
    - cd build
    - cmake ..
    - make
after_script:
    - make clean

